version: '3.7'

networks:
  csvimporter:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: csvimporter-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - csvimporter

  db:
    image: mysql:5.7.22
    container_name: csvimporter-db
    restart: unless-stopped
    tty: true
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: csvimporter
      MYSQL_USER: csvimporter
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: ${APP_SERVICE_TAGS}
      SERVICE_NAME: mysql
    networks:
      - csvimporter

  app:
    build:
      args:
        user: ${APP_USER}
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: csvimporter-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "9005:9000"
    networks:
      - csvimporter

  node:
    build:
      context: ./
      dockerfile: ./node/Dockerfile
      args:
        user: ${APP_USER}
    container_name: csvimporter-node
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - csvimporter
